/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
  id("java-library") // Semicolon added, ID in parentheses
  id("maven-publish") // Semicolon added, ID in parentheses
}

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
    implementation("org.postgresql:postgresql")
  implementation("org.springframework.boot:spring-boot-starter-security")
  implementation ("org.springframework.boot:spring-boot-starter-actuator")
  implementation ("org.springframework.boot:spring-boot-starter-data-jpa")
  implementation ("org.springframework.boot:spring-boot-starter-thymeleaf")
  implementation ("org.springframework.boot:spring-boot-starter-web")
  implementation ("org.thymeleaf.extras:thymeleaf-extras-springsecurity6")
  runtimeOnly("org.springframework.boot:spring-boot-devtools")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  testImplementation ("org.springframework.security:spring-security-test")
}

group = "com.autonomo"
version = "0.0.1-SNAPSHOT"
description = "miproyecto"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

publishing {
  publications {
    create<MavenPublication>("maven") {
      // ... configure publication details
    }
  }
}

tasks.withType<JavaCompile> {
  options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
  options.encoding = "UTF-8"
}

